### PR TITLE
Automatically generate projects, refs #7

### PR DESCRIPTION
**Pull request by zupo**
* projects in top nav, on index page and on ``/projects.html`` page are now built dynamically from projects.json file
* projects that have ``"display_on_index": true`` are shown on index page
* projects that have ``"display_in_nav": true`` are shown in top navigation, but then they should have ``websiteUrl`` set as well
* projects that have ``"deprecated":true`` are shown in the bottom section of the ``/projects.html`` page.
* added many other projects, such as SubstanceD, WebTest, AcidFS, ...

screen_shot_2016-12-07_at_19_47_50
screen_shot_2016-12-07_at_19_48_06

### CODE REVIEW

**Comment by bertjwregeer** [comment]
Can we make all project boxes the same size? It looks really messy with each one having a different size.

**Comment by blaflamme** [comment]
One thing is for sure to make description as concise as possible. As an example WebTest description tells too much for what we need to know about. The doc page will tell more after. I propose to have not more than 2 lines for descriptions for those boxes .

**Comment by zupo** [comment]
@blaflamme: shortened descriptions

@bertjwregeer: it looks worse to me:

screen shot 2016-12-08 at 11 23 45


Anything else or can I merge?

**Comment by blaflamme** [comment]
@zupo having the remaining space at the end of the box is not great. You should make the Package/Source/Docs section bottom aligned, then the pace will fit between that and the description. You'll also have to make sure the description section is not more than 3 lines.

**Comment by zupo** [comment]
I am *very* rusty with my CSS, could you possibly help out?

**Comment by blaflamme** [comment]
@zupo sure... I'll work on this.

**Comment by zupo** [comment]
Awesome, fell free to merge when you are done.

**Pull request merged**
