### PR TITLE
Fill up top navigation

### PR DESCRIPTION
**Pull request by zupo**
screen shot 2016-12-06 at 14 13 19

### CODE REVIEW

**Comment by zupo** [comment]
@stevepiercy, @blaflamme: suggestion on where to point the Projects -> Pylons link to?

**Comment by blaflamme** [comment]
@zupo http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/ ?

**Comment by blaflamme** [comment]
zupo it should also be named Pylons Web Framework, to make it different than Pylons Project

**Comment by zupo** [comment]
@blaflamme: that's where it points already, so all good

Renamed ``Pylons`` to ``Pylons Web Framework``. Should I do the same with ``Pyramid``? So we have ``Pyramid Web Framework`` and ``Pylons Web Framework`` instead of ``Pyramid`` and ``Pylons Web Framework`` .

**Comment by blaflamme** [comment]
@zupo I'll just keep `Pyramid`. For `Pylons` it's trickier since we have both the organization and the `deprecated` framework, while no mention of `deprecated` is visible. That's why I would add `Web Framework` or just `Framework`. Also I'm not sure we should put it under `Projects`, I see them more as `active` projects, so could it belongs elsewhere like under about or part of history?

**Comment by zupo** [comment]
About would then be:
* Pylons Project
* Pylons Web Framework
* History
* License

Which does make a lot of sense to me, yes. And make it point to a subpage, such as this one: http://www.pylonsproject.org/projects/pylons-framework/about

**Comment by blaflamme** [comment]
I also think it's better that way and yes that pylons page was done for that back in time.

**Comment by zupo** [comment]
@blaflamme: updated. Also added ``(deprecated)``.

**Pull request merged**
