### PR TITLE
Add 404.html

### LINKED ISSUE #64: Add 404.html

### PR DESCRIPTION
**Pull request by stevepiercy**
- Update README.md with correct commands

Closes #64

### CODE REVIEW

**Comment by mmerickel** [comment]
This isn't the right way to add a 404 to Hugo. It's special and you can just add it directly to the layout.

**Comment by stevepiercy** [comment]
Woops. Didn't see your note before merging.

**Comment by stevepiercy** [comment]
FWIW, it does work, although it's not the right way. https://pylonsproject.org/moo

Should I delete 404.md?

**Comment by stevepiercy** [comment]
Yup, that seems to work, too. See #84.

**Pull request merged**
